spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://svc.sel3.cloudtype.app:30663/mariadb?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect