server.port=8080
spring.profiles.active=prod

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

logging.level.com.example.EquipmentRentalSystem=DEBUG
jwt.secret=my_secret_key_for_equipment_rental_system_2026_03_06
jwt.expiration=86400000
