spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.url=${DB_URL:jdbc:h2:file:/data/testdb;MODE=MySQL;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=Asia/Seoul
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always